### ISSUE TITLE
hveto crashes upon making summary plots if no rounds are completed

### ISSUE THREAD

**Issue by duncanmmacleod** [hveto/hveto#17]
The `hveto` executable raises a `NameError` if exactly zero rounds were completed above the minimum significance:

```
[hveto 1145311502]    DEBUG: Making summary figures...
Traceback (most recent call last):
  File "/home/duncan.macleod/opt/gwpysoft-2.7/bin/hveto", line 487, in <module>
    label1='Before round 1', label2=afterl, xlabel=statlabel,
NameError: name 'afterl' is not defined
```

**Comment by duncanmmacleod** [comment]
@jrsmith02: this is easy to work around by only plotting stuff if at least 1 round went through above the threshold, but what output do you actually want in that case?

Presumably something akin to the old version, just with an HTML snippet saying 'no rounds completed above threshold'?

**Comment by jrsmith02** [comment]
Good question. Yes, the Matlab hveto makes an html page like you describe. However, that could be improved: if no rounds pass the threshold, it would still be interesting to say what the highest significance channel, threshold, twin is. That would help debug further what went wrong.
