### ISSUE TITLE
hveto should allow reading the DAC crossing triggers as auxiliary channels

### ISSUE THREAD

**Issue by jrsmith02** [hveto/hveto#18]
TJ Massinger developed code that looks at data for all of LIGO's 18-bit Digital to Analog Converters and checks for times when the values cross 'special' values like zero or 2^16, known as major carry transitions, and may cause glitches. These times are written as "triggers" in ligolw_xml files using the same general form singl_burst as Omicron triggers. Python hveto should be able to optionally read in these sort of DAC crossing triggers. 

An example use case of this is described in ref#71 on the GW150914 detection checklist: 
https://docs.google.com/spreadsheets/d/1w-VTSGe_bwt71ar-4W-0du4dq2tiylKZpiYkW7THL5k/edit?userstoinvite=siddheshpai@gmail.com&actionButton=1#gid=425080531 

An example webpage of the results is here: https://ldas-jobs.ligo-wa.caltech.edu/~hveto/daily/201509/20150914/H1-omicron_BOTH-1126224017-86400-DAC/ I think the DAC crossing triggers used were located here: auxRawTrigDir = /home/tjmassin/DAC_MCT_trigs/ER8

Note, I think that this should work by pointing hveto to the appropriate trigger location, and appropriately annotating on the page the type of aux channel triggers (DAC crossing) that are being used.

**Comment by duncanmmacleod** [comment]
@jrsmith02, I think this will be provided by whatever code implements #8, plus a little addition as requested to annotate on the output page what the 'trigger-generator' was for this set.
