### ISSUE TITLE
Store results in plaintext format

### ISSUE THREAD

**Issue by duncanmmacleod** [hveto/hveto#20]
It might be nice to store the basic results table in a more plaintext format, showing the name, significance, SNR, dt, etc. of each round winner, linking to the segment file for each round, and possibly other files.

Perhaps JSON is the most transparent format for this? It would allow other tools to pick up the results and use them if they want.

**Comment by jrsmith02** [comment]
I agree. Matlab hveto has a plain text results table output that might be a starting point for this. You can reach it off the main page under “results table [txt]”
For example, on this page: 
https://ldas-jobs.ligo-wa.caltech.edu/~jrsmith/hveto/O1/analysis9/H1-omicron_BOTH-1135652417-1602000-DARM/
That link points to 
https://ldas-jobs.ligo-wa.caltech.edu/~jrsmith/hveto/O1/analysis9/H1-omicron_BOTH-1135652417-1602000-DARM/summary_stats.txt
Is that along the lines of what you meant, perhaps with a header line?

**Comment by duncanmmacleod** [comment]
@jrsmith02, basically. But, perhaps we can have both, a simple txt format of the table, and a JSON file that links everything together. I'll try and mock up an example of my idea so you can see a little better.

**Comment by jrsmith02** [comment]
Sounds like a great idea to me!
