### ISSUE TITLE
Allow a custom set of analysis segments

### ISSUE THREAD

**Issue by duncanmmacleod** [hveto/hveto#24]
Currently the only route to specify the analysis segments for `hveto` is to use the `analysis-flag` option in the configuration file. It might be nice to allow a `--analysis-segments` option for people to pass in their targeted segment lists, rather than querying the database.

This might also be useful for the eventual `hveto-safety` implementation.

@hveto/developers, any objections?

**Comment by jrsmith02** [comment]
We definitely want this option, thanks for bringing it up. We do this by hand in Matlab hveto sometimes by generating a segments file with the right name and putting it in the output directory. Since hveto checks for the existence of that file before getting segments. But your optional argument plan is better.

**Comment by jrsmith02** [comment]
Another use case would be for creating vetoes for Burst and CBC searches, where we might want to optionally use ANALYSIS-READY - CATS1,2,3,4. For the hveto reruns for the burst group, for example, I did this with this procedure: 

```
C) Get the segments. 

[jrsmith@ldas-pcdev1 bin]$ ligolw_segments_from_cats_dqsegdb --veto-file H1L1-HOFT_C01_O1_BURST.xml -s 1133173817 -e 1134450017 --cumulative-categories --segment-url https://segments.ligo.org

D) Turn these veto segments into positive segments to be analyzed by hveto. Done by taking analysis ready - these segments.

[jrsmith@ldas-pcdev1 bin]$ python science_minus_flag_nicer -i H1 -s 1133173817 -d 1276200 -f H1-VETOTIME_CAT4-1133173817-1276200.xml 

Move last segments and omicron directory: 

[jrsmith@ldas-pcdev1 bin]$ cd ~/joework/
[jrsmith@ldas-pcdev1 joework]$ mv testTrig/ testTrig-analysis6
[jrsmith@ldas-pcdev1 joework]$ mv testTrig-analysis6/ old/
[jrsmith@ldas-pcdev1 joework]$ mkdir testTrig
[jrsmith@ldas-pcdev1 joework]$ cd ~/svn/HierarchichalVeto/bin/
[jrsmith@ldas-pcdev1 bin]$ cp H1-SCIENCE_MINUS_VETO-1133173817-1276200.xml ~/joework/testTrig/segs.xml
```
