### ISSUE TITLE
Make main channel triggers after cuts but before round 1 available on page

### ISSUE THREAD

**Issue by jrsmith02** [hveto/hveto#33]
It would be useful to generate a file, e.g., L1-HVETO_RAW_TRIGS_ROUND_0-1134604817-86400.txt (in the "triggers" subdirectory of the results page), which is the set of primary triggers that pass DQ flags and SNR and frequency cuts, i.e. the primary triggers before round 1. That would be a useful file to see the starting hveto triggers, and could perhaps be posted to the page somewhere “starting primary triggers [txt]”. 

In Matlab hveto this is unlinked, but I use the file a lot. It’s name is the same as “Unvetoed primary triggers [txt]” except that the file is *RAW_TRIGS_ROUND_0*. Example: https://ldas-jobs.ligo-la.caltech.edu/~hveto/daily/201512/20151220/L1-omicron_BOTH-1134604817-86400-DARM/L1-HVETO_RAW_TRIGS_ROUND_0-1134604817-86400.txt

**Comment by duncanmmacleod** [comment]
This was provided by #32 (7d716fa).
