### ISSUE TITLE
Idea for hveto time scan utility

### ISSUE THREAD

**Issue by duncanmmacleod** [hveto/hveto#40]
I had an idea for a small utility for the hveto package, namely a tool that takes in a GPS time and some reference to an hveto analysis, and returns to the user whether the time in question would have been vetoed by that analysis, and at which round. Something like:

```
$ hveto-trace 1126259462
1126259462 not vetoed
$ hveto-trace <bad time>
<bad time> vetoed at round 4
```

Using the `summary-stats.json` file to iterate over the rounds and compare the input time to the veto segments for each round should make this fairly simple, but very useful.

**Comment by jrsmith02** [comment]
wonderful. I would like a --verbose option that works like: 

$ hveto-trace 1126259468
1126259468 vetoed at round 4 by H1:PEM-EY_MAG_Z, significance 8092.3, twin=0.1s, SNR>8.0, url=https:///url-for-that-hveto-page#that-round 

Or something similar.
