### ISSUE TITLE
Drop plot is very hard to read

### ISSUE THREAD

**Issue by duncanmmacleod** [hveto/hveto#5]
The significance drop plot (example below) is very hard to read most of the time, because of the number of channels.

![example](https://cloud.githubusercontent.com/assets/1618530/14001134/88836ea4-f112-11e5-8925-e30101660f53.png)

Possible solutions include using svg (or other such fancy technology) to show the channel and significance when you hover over the points on the figure.

Or, we could just not show channels on the drop plot that don't drop (i.e. remove the red dots), or remove all channels with a starting significance less than the stopping threshold? @jrsmith02, any thoughts?

**Comment by jrsmith02** [comment]
The easiest way to win greatly is to not show any channel that has zero significance in round 1. So before creating the drop plot, prune the plotted channels to those with Sig>0. Has that already been applied here?

**Comment by duncanmmacleod** [comment]
@jrsmith02 no, do you mean just to remove them from the plot, or can we remove them from the analysis entirely (this shouldn't really save any computation time, but might clean things up a wee bit).

I presume a significance of 0 can only happen when the aux channel has zero events in it (or the primary has zero events)?

**Comment by jrsmith02** [comment]
A significance of zero can only happen when an aux channel has no coincidences with the main channel within a given time window. 

If an aux channel were to have no coincidences in round 1 with the main channel, for the largest time window and lowest threshold in the conf, it would have to have zero significance for all future rounds. 

Therefore, I'd suggest dropping any channel with zero significance in round 1 for the lowest threshold and largest time window from the drop plot and the rest of the analysis.

**Comment by duncanmmacleod** [comment]
ok, I can do that.

**Comment by duncanmmacleod** [comment]
@jrsmith02: should we remove channels with zero significance after _all_ rounds, or just round 1?

**Comment by jrsmith02** [comment]
I suppose we could do that same check after every round. I expect the vast majority of the removals to be after the first round though.

**Comment by duncanmmacleod** [comment]
this was fixed by #35
