### ISSUE TITLE
ifo argument missing from omega scan options and omega location not obvious

### ISSUE THREAD

**Issue by lauranuttall** [hveto/hveto#50]
When running hveto after you have sourced a gwpy environment the script fails because I did not export the omega scan location: export OMEGA_LOCATION=/home/omega/opt/omega
Can this be done automatically? Appear in the help message? Appear in the documentation?

When generating the dag for the omega scans the script right now forgets to add in the ifo argument.

**Comment by duncanmmacleod** [comment]
@lauranuttall, can you post a command-line to reproduce?

**Comment by lauranuttall** [comment]
Hmmm can't produce the first error. Never mind.

But the second one - on LLO in /home/laura.nuttall/public_html/detchar/hveto/1158809069_1158849063/scans/condor/wdq-batch.sh for example and you will see no --ifo option. If you try to run that script it fails because there's no --ifo option
