### ISSUE TITLE
Reported use percentage does not seem to be correct

### ISSUE THREAD

**Issue by jrsmith02** [hveto/hveto#55]
For this page: 

https://ldas-jobs.ligo-la.caltech.edu/~tjmassin/hveto/GSpy/O1/L1-GSpy-Blip-test-1126403702-604800-omega/

round 1 reports 0/11 = 0 use percentage. However, the round 1 plots indicate that 11 triggers were used to veto 5 events. 

https://ldas-jobs.ligo-la.caltech.edu/~tjmassin/hveto/GSpy/O1/L1-GSpy-Blip-test-1126403702-604800-omega/plots/L1-HVETO_USED_FREQUENCY_TIME_ROUND_1-1126403702-604800.png

So the used percentage should not be zero. It should be the number of triggers actually used to veto one h(t) triggers. Which is maximum 5 (assuming we choose one unique trigger for each vetoed h(t) trigger.

**Comment by duncanmmacleod** [comment]
This issue is caused because the input primary trigger set is not time ordered. I am about to submit a PR to force a sorting when the triggers are read.
